openapi: 3.0.0
info:
  title: Bluehost Deployment Client
  description: the deployment client api
  contact:
    email: admin@bluehost.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: v1
servers:
  - url: /api/v1
    description: Bluehost Deployment Client
paths:
  /:
    get:
      summary: get healthcheck
      operationId: dclient.controllers.healthcheck.get_healthcheck
      responses:
        "200":
          description: health is good
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/HealthCheck'
  /rollout:
    post:
      summary: create a rollout
      operationId: dclient.controllers.rollout.post_rollout
      requestBody:
        description: Create Rollout object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RollOut'
        required: true
      responses:
        default:
          description: successful operation
  /rollback:
    post:
      summary: create a rollback
      operationId: dclient.controllers.rollback.post_rollback
      requestBody:
        description: Create Rollback object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RollBack'
        required: true
      responses:
        default:
          description: successful operation
  /update:
    post:
      summary: issue an update
      operationId: dclient.controllers.update.post_update
      requestBody:
        description: Update a Server
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Update'
        required: true
      responses:
        default:
          description: successful operation
  /versionlock:
    post:
      summary: create a versionlock
      operationId: dclient.controllers.versionlock.post_versionlock
      requestBody:
        description: Create Versionlock object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VersionLock'
        required: true
      responses:
        default:
          description: successful operation
    get:
      summary: get versionlock
      operationId: dclient.controllers.versionlock.get_versionlock
      responses:
        "200":
          description: get server's versionlock data
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/VersionLock'
components:
  schemas:
    HealthCheck:
      type: object
      properties:
        id:
          type: integer
          example: 1
        status:
          type: string
          example: good
        created_at:
          type: string
          example: 2020-07-26T17:16:29.051842
    RollOut:
      type: object
      properties:
        buildall:
          type: boolean
          default: False
        deployment_id:
          type: integer
          example: 1
        versionlock:
          type: array
          example: ["httpd-2.4.6-93.el7.centos.x86_64", "mod_perl-2.0.11-1.el7.x86_64"]
    RollBack:
      type: object
      properties:
        buildall:
          type: boolean
          default: False
        deployment_id:
          type: integer
          example: 1
        versionlock:
          type: array
          example: ["httpd-2.4.6-93.el7.centos.x86_64", "mod_perl-2.0.11-1.el7.x86_64"]
    Update:
      type: object
      properties:
        packages:
          type: array
          example: ["dclient"]
    VersionLock:
      type: object
      properties:
        hostname:
          type: string
          example: www0.hp.provo1.endurancemb.com
        versionlock:
          type: array
          example: ["httpd-2.4.6-93.el7.centos.x86_64", "mod_perl-2.0.11-1.el7.x86_64"]