openapi: 3.0.0
info:
  title: Bluehost Deployment Client
  description: the deployment client api
  contact:
    email: admin@bluehost.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: v1
servers:
  - url: /api/v1
    description: Bluehost Deployment Client
paths:
  /:
    get:
      summary: get healthcheck
      operationId: dclient.controllers.healthcheck.get_healthcheck
      responses:
        "200":
          description: health is good
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/HealthCheck'
  /rollout:
    post:
      summary: create a rollout
      operationId: dclient.controllers.rollout.post_rollout
      requestBody:
        description: Create Rollout object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RollOut'
        required: true
      responses:
        default:
          description: successful operation
  /rollback:
    post:
      summary: create a rollback
      operationId: dclient.controllers.rollback.post_rollback
      requestBody:
        description: Create Rollback object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RollBack'
        required: true
      responses:
        default:
          description: successful operation
  /update:
    post:
      summary: create an update
      operationId: dclient.controllers.update.post_update
      requestBody:
        description: Create an update object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Update'
        required: true
      responses:
        default:
          description: successful operation
  /versionlock:
    get:
      summary: get versionlock list
      operationId: dclient.controllers.versionlock.get_versionlock
      responses:
        "200":
          description: get versionlock list
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/VersionLock'
components:
  schemas:
    HealthCheck:
      type: object
      properties:
        id:
          type: integer
          example: 1
        status:
          type: string
          example: good
        created_at:
          type: string
          example: 2020-07-26T17:16:29.051842
    RollOut:
      type: object
      properties:
        server_id:
          type: integer
          example: 1
        deployment_id:
          type: integer
          example: 1
        action:
          type: string
          example: UPDATE
        output:
          type: string
          example: deployment was successful
        yum_transaction_id:
          type: integer
          example: 1
        yum_rollback_id:
          type: integer
          example: 1
    RollBack:
      type: object
      properties:
        server_id:
          type: integer
          example: 1
        deployment_id:
          type: integer
          example: 1
        action:
          type: string
          example: UPDATE
        output:
          type: string
          example: deployment was successful
        yum_transaction_id:
          type: integer
          example: 1
        yum_rollback_id:
          type: integer
          example: 1